project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Economic Research Methods"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Content"
        file: content.qmd
      - text: "Project"
        file: research-project.qmd
      - text: "Assignments"
        file: assignments.qmd
  
  page-footer:
      2024 Div Bhagia | [CC BY-NC 4.0 License](https://creativecommons.org/licenses/by-nc/4.0/) |Made with [Quarto](https://quarto.org/)
  
format:
  html:
    theme: assets/custom.scss
    toc: true
    link-external-newwindow: true
    css: assets/styles.css
