project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Econ 340: Economic Research Methods"
  navbar:
    right:
      - text: "Overview"
        file: index.qmd
      - text: "Lecture Materials"
        file: lecture-materials.qmd
      - text: "Research Project"
        file: research-project.qmd
      - text: "Problem Sets & Exams"
        file: problem-sets-exams.qmd
      - icon: github
        href: https://divbhagia.github.io/Econ340/
  page-footer: "All material is shared under the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/){target='_blank'} license."
  
format:
  html:
    theme: custom.scss
    toc: true
    link-external-newwindow: true