project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Lectures/"
  
execute:
  freeze: auto

website:
  title: "Economic Research Methods"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus.qmd
      - text: "Content"
        file: content.qmd
      - text: "Assessment"
        file: assessment.qmd
      - text: "Project"
        file: Research-Project/research-project.qmd
  
  sidebar:
    - title: "Research Project"
      style: "docked"
      search: false
      contents:
        - text: "Overview"
          file: Research-Project/research-project.qmd
        - text: "Interim Submission I"
          file: Research-Project/interim-submission1.qmd
        - text: "Interim Submission II"
          file: Research-Project/interim-submission2.qmd
        - text: "Final Submission"
          file: Research-Project/final-submission.qmd
  
  page-footer:
      2024 Div Bhagia | [CC BY-NC 4.0 License](https://creativecommons.org/licenses/by-nc/4.0/) |Made with [Quarto](https://quarto.org/)
  
format:
  html:
    theme: assets/custom.scss
    toc: true
    link-external-newwindow: true
    css: assets/styles.css
