---
title: "Assessment"
sidebar: false
---

Your performance in this class will be evaluated based on active engagement, four problem sets, two exams, and your research project. Below, you will find the problem sets; please submit your solutions on Canvas. Solutions to the problem sets will be posted on Canvas following the due date. Additionally, study guides and sample exams for both the midterm and final exam are available below. 
Details for the research project submissions can be found on the [Project](Research-Project/research-project.html) page.

### Problem Sets

- [Problem Set 1](Problem-Sets/PS1/PS1.pdf)
- [Problem Set 2](Problem-Sets/PS2/PS2_Raw/ps2.pdf) (Download [zippped folder](Problem-Sets/PS2/PS2.zip) with datasets and R Code to complete.)
- [Problem Set 3](Problem-Sets/PS3/PS3.pdf)
- [Problem Set 4](Problem-Sets/PS4/PS4.pdf)

### Exam Material

- Midterm
  - [Study Guide](Exams/Midterm/midterm_study_guide.pdf)
  - [Midterm Review Slides](Lectures/Midterm-Review/midterm_review.pdf)
  - Compiled material for Modules I, II, IV: [Notes](Notes/Part1-Compiled-Notes.pdf), [Handouts](Lectures/Part1-Compiled-Handouts.pdf), [Slides](Lectures/Part1-Compiled-Slides.pdf)
  - [Sample Exam](Exams/Midterm/midterm_sample.pdf)
  - [Sample Exam Solutions](Exams/Midterm/midterm_sample_solutions.pdf)
  - [Formula Sheet](Exams/Midterm/midterm_formula_sheet.pdf)<br>
<br>

- Final
  - [Sample Exam](Exams/Final/final_sample.pdf)
  - [Sample Exam Solutions](Exams/Final/final_sample_solution.pdf)
  - [Study Guide](Exams/Final/final_study_guide.pdf)
  - [Sample Questions for Module VI](Exams/Final/sample_questions_add_topics.pdf)
