---
title: "Lecture Materials"
sidebar: false
---

### Module I: Describing Data 

[Lecture Notes](Notes/Module1-Intro-and-Describing-Data/Describing-Data.pdf)

- Lecture 1: Introduction; Summation Notation [[slides](Lectures/Lecture1/Slides1.pdf), [handout](Lectures/Lecture1/ClassHandout1.pdf) [(filled)](Lectures/Lecture1/ClassHandout1_Filled.pdf)]
- Lecture 2: Distribution, Mean, Median, Percentiles [[slides](Lectures/Lecture2/Slides2.pdf), [handout](Lectures/Lecture2/ClassHandout2.pdf) [(filled)](Lectures/Lecture2/ClassHandout2_Filled.pdf)]
- Lecture 3: Variance, Standard Deviation, Z-Score [[slides](Lectures/Lecture3/Slides3.pdf), [handout](Lectures/Lecture3/ClassHandout3.pdf) [(filled)](Lectures/Lecture3/ClassHandout3_Filled.pdf)]
- Lecture 4: Covariance and Correlation [[slides](Lectures/Lecture4/Slides4.pdf), [handout](Lectures/Lecture4/ClassHandout4.pdf) [(filled)](Lectures/Lecture4/ClassHandout4_Filled.pdf)]
- Lecture 5: Research Questions and Data [[slides](Lectures/Lecture5/Slides5.pdf)]

Additional Reading: [NYT Article 2016 Elections](Readings/NYT-Article-2016-Elections.pdf), [Stock & Watson Chapter 1](Readings/Stock-&-Watson-Chapter1.pdf)

### Module II: Coding in R
Here are the [instructions](Notes/How-to-install-R.pdf) for installing R and R Studio. You can find the datasets used in class in the Dropbox folder: [Econ340 Datasets](https://www.dropbox.com/sh/9x7ac4qwnddl650/AAAP1FdTpFp2rXyZ6t-9-qqTa?dl=0).

Click [here](Data/lectures6-8.zip) to download the folder containing the dataset and initial R script for lectures 6-8.

- Lecture 6: Getting Started with R [[slides](Lectures/Lecture6-8/Slides6.pdf)]
- Lecture 7: Data Analysis in R [[slides](Lectures/Lecture6-8/Slides7.pdf)]
- Lecture 8: Data Analysis in R [[slides](Lectures/Lecture6-8/Slides8.pdf)]

### Module III: Random Variables

[Lecture Notes](Notes/Module3-Random-Variables/Random-Variables.pdf)

- Lecture 9: Distribution, Expectation, Variance [[slides](Lectures/Lecture9/Slides9.pdf), [handout](Lectures/Lecture9/ClassHandout9.pdf) [(filled)](Lectures/Lecture9/ClassHandout9_Filled.pdf)]
- Lecture 10: Normal Distribution, Z-Score [[slides](Lectures/Lecture10/Slides10.pdf), [handout](Lectures/Lecture10/ClassHandout10.pdf) [(filled)](Lectures/Lecture10/ClassHandout10_Filled.pdf), [z-table](Lectures/Lecture10/z_table.pdf)]
- Lecture 11: Independence and Correlation [[slides](Lectures/Lecture11/Slides11.pdf), [handout](Lectures/Lecture11/ClassHandout11.pdf) [(filled)](Lectures/Lecture11/ClassHandout11_Filled.pdf)]

### Module IV: Sampling and Estimation

[Lecture Notes](Notes/Module4-Sampling-and-Estimation/Sampling-and-Estimation.pdf), [CLT Simulation](https://dbhagia.shinyapps.io/CLT-Demo/)

- Lecture 12: Good Estimators, Sample Mean Distribution [[slides](Lectures/Lecture12/Slides12.pdf), [handout](Lectures/Lecture12/ClassHandout12.pdf) [(filled)](Lectures/Lecture12/ClassHandout12_Filled.pdf)]
- Lecture 13: Confidence Intervals [[slides](Lectures/Lecture13/Slides13.pdf), [handout](Lectures/Lecture13/ClassHandout13.pdf) [(filled)](Lectures/Lecture13/ClassHandout13_Filled.pdf)]
- Lecture 14: Hypothesis Testing and P-Values [[slides](Lectures/Lecture14/Slides14.pdf), [handout](Lectures/Lecture14/ClassHandout14.pdf) [(filled)](Lectures/Lecture14/ClassHandout14_Filled.pdf)]

### Module V: Linear Regression

Notes: [Lectures 15-17](Notes/Module5-Linear-Regression/Simple-Linear-Regression.pdf), [Lecture 18 I](Notes/Module5-Linear-Regression/Omitted-Variable-Bias.pdf) & [II](Notes/Module5-Linear-Regression/Multiple-Linear-Regression.pdf), [Lecture 19](Notes/Module5-Linear-Regression/Dummy-Variables-and-Interaction-Terms.pdf),  [Lecture 20](Notes/Module5-Linear-Regression/Functional-Forms.pdf)

- Lecture 15: Ordinary Least Squares (OLS); R-Squared [[slides](Lectures/Lecture15/Slides15.pdf), [handout](Lectures/Lecture15/ClassHandout15.pdf) [(filled)](Lectures/Lecture15/ClassHandout15_Filled.pdf)] 
- Lecture 16: Prediction vs. Causal Inference [[slides](Lectures/Lecture16/Slides16.pdf)]
- Lecture 17: Inference (p-values, t-stats, confidence intervals) [[slides](Lectures/Lecture17/Slides17.pdf), [handout](Lectures/Lecture17/ClassHandout17.pdf) [(filled)](Lectures/Lecture17/ClassHandout17_Filled.pdf)]
- Lecture 18: Omitted Variable Bias; Multiple Regression [[slides](Lectures/Lecture18/Slides18.pdf), [handout](Lectures/Lecture18/ClassHandout18.pdf)]
- Lecture 19: Categorical Variables; Interaction Terms [[slides](Lectures/Lecture19/Slides19.pdf), [handout](Lectures/Lecture19/ClassHandout19.pdf) [(filled)](Lectures/Lecture19/ClassHandout19_Filled.pdf)]
- Lecture 20: Quadratic and Log Functional Forms [[slides](Lectures/Lecture20/Slides20.pdf), [handout](Lectures/Lecture20/ClassHandout20.pdf) [(filled)](Lectures/Lecture20/ClassHandout20_Filled.pdf)]
- Lecture 21: Regression Analysis in R [[slides](Lectures/Lecture21-22/Slides21.pdf)]
- Lecture 22: Regression Analysis in R [[slides](Lectures/Lecture21-22/Slides22.pdf)]

Click [here](Data/lectures21-22.zip) to download the folder containing the datasets and R scripts for lectures 21 and 22.

### Module VI: Advanced Topics
- Lecture 23: Experiments and Quasi-Experimental Methods [[slides](Lectures/Lecture23/Slides23.pdf)]
- Lecture 24: Differences-in-Differences [[slides](Lectures/Lecture24/Slides24.pdf)]
- Lecture 25: Big Data and Machine Learning [[slides](Lectures/Lecture25/Slides25.pdf)]
  
Additional Reading: [2021 Nobel Prize in Economics](Readings/popular-economicsciencesprize2021.pdf), [Trade War](https://microeconomicinsights.org/the-return-to-protectionism/)