---
title: "Syllabus"
toc: false
number-sections: false
sidebar: false
format: html
---

The key components of the syllabus are outlined below. You can access the complete syllabus in PDF format by clicking [here](Syllabus/Econ340Syllabus.pdf).

::: {.panel-tabset}

## Overview
### Overview

This course covers the basics of conducting quantitative economic research. The course aims to take you through the steps involved in answering a research question using observational data. You will learn and implement statistical and econometric concepts vital to empirical research. You will select a question, locate data to answer it and use the tools we learn in this class to answer this question.

This course will involve hands-on work with data using *R*, a statistical software, both inside and outside the classroom. The tools learned in this class will be helpful regardless of whether your goal is to be a researcher, a consultant, run your own business, or work for a non-profit.

## Learning Goals
### Learning Goals
Upon successful completion of this course, students will be able to discern valuable insights from datasets and communicate empirical findings effectively. In particular, you will

- Develop a strong grasp of both the conceptual and practical aspects of various statistical and econometric tools.
- Learn to tidy, wrangle, manipulate, and visualize data using [TidyVerse](https://www.tidyverse.org) in R.
- Be able to compute descriptive statistics, perform regression analysis in R, and present results in a clear, elegant manner.
- Gain the skill to effectively communicate empirical findings.
- Develop an understanding of causality, including the ability to identify and articulate potential threats to causal inference
- Get an introduction to advanced topics at the forefront of economic research, such as quasi-experimental methods and machine learning.

## Course Structure
### Course Structure

All meetings for this course are expected to take place in a physical classroom. During class, in addition to my delivering the day’s topics via lecture slides, you will often be expected to engage in collaborative problem-solving with handouts, work on R programming exercises, and participate in class discussions. The course is designed to be interactive, and requires you to actively participate. Therefore, regular class attendance is especially important for you to suceed in this class.

A significant portion of this class is focused on developing a research paper, which you can complete individually or with a classmate. You can either choose your own dataset or use one of the datasets that I have compiled for this class in the [Econ340 Datasets](https://www.dropbox.com/sh/9x7ac4qwnddl650/AAAP1FdTpFp2rXyZ6t-9-qqTa?dl=0) Dropbox folder. You’ll begin the research project early in the semester, with assignments focused on formulating a question, selecting data, and conducting descriptive analysis. I’ll provide guidance and support throughout the semester and will schedule a mid-semester meeting to review your progress.

## Material
### Course Material

All course materials—including lecture slides, handouts, notes for each topic—are available on the course website. These materials should generally be sufficient, and there is no mandatory textbook for this class. However, if you have a keen interest in the subject and seek additional references, the following options are great choices:

- Stock J, Watson M. Introduction to Econometrics (3rd edition)
- Huntington-Klein, Nick. 2021. The Effect: An Introduction to Research Design and Causality [https://theeffectbook.net/](https://theeffectbook.net/)
- Cunningham, Scott. Causal Inference: The Mixtape [https://mixtape.scunning.com](https://mixtape.scunning.com)


## Grading

### Grading Criteria

Your course grade will be determined according to the following breakdown:

<table style="margin-left: auto; margin-right: auto; width: 70%;">
  <tr>
    <th style="width: 70%; text-align: left;">Component</th>
    <th style="width: 30%;">Points</th>
  </tr>
  <tr>
    <td style="text-align: left;">Active Engagement</td>
    <td>10</td>
  </tr>
  <tr>
    <td style="text-align: left;">Problem Sets</td>
    <td>20</td>
  </tr>
  <tr>
    <td style="text-align: left;">Research Paper: Interim Submissions </td>
    <td>15</td>
  </tr>
  <tr>
    <td style="text-align: left;">Research Paper: Final Submission </td>
    <td>15</td>
  </tr>
  <tr>
    <td style="text-align: left;">Midterm Exam</td>
    <td>20</td>
  </tr>
  <tr>
    <td style="text-align: left;">Final Exam</td>
    <td>20</td>
  </tr>
</table>


:::