---
title: "Research Project: Interim Submission"
---

## Introduction

This submission marks the beginning of your research project. Prior to moving forward, kindly review the [Research Project Overview](research-project.qmd) page, which provides guidance on the choice of question and data.

For this submission, you need to (a) describe your research question and the data you will use, and (b) perform a basic analysis of your data in R. You will highlight why your question is interesting and important, mention your data sources, and identify the variables you will use. Then, report the key numerical characteristics of your variables and conduct some visual analysis. The aim is to gain an overall understanding of the patterns in your data. This submission will serve as a foundation for writing the "Introduction" and "Descriptive Analysis" sections of your final paper.

Below, I detail the specific [tasks](#tasks) you need to complete and what you are required to [submit](#submission-checklist). At the bottom of the page, you'll also find a [rubric](#rubric) that will be used for grading. Finally, here is an [example submission](submission1-example.pdf) with it's corresponding [R code](submission1-example-code.R) to guide you. Please use this as a reference only; any sentences directly copied from the example submission will be considered plagiarism.  

**Before you get started:**

- Confirm that your question has been defined to examine the effect of one variable (**the primary independent variable**) on another (**the dependent variable**). Additionally, you should have identified **at least two control variables** that may be correlated with both the primary independent and dependent variables. See the [section on variables](research-project.qmd#variables) on the [overview](research-project.qmd) page for more details. 
- Ensure that the dataset you've selected contains all the above variables and has **at least 100 observations**.

## Tasks 

For all tasks except the first one, ensure your responses are structured in paragraphs and categorized into sections. Consult the example submission for formatting guidance.

1. **Cover Sheet**: Complete this [cover sheet](ubmission1-cover-sheet.docx) and attach it as the first page of your submission.
2. **Introduction**: Clearly specify your research question and explain why it interesting or important.
3. **Data and Variables Description**: Mention and verbally describe the dataset you are using, your dependent variable, primary independent variable, and control variables. Your variables should be either continuous or binary. If your variable is categorical and has more than two categories, transform it into a meaningful binary variable using 1 and 0 as values. Remember to mention how the variables are named in your dataset. Mention if you constructed new variables or deleted observations. Also, note the number of observations in your data.
4. **Summary Statistics**: Present summary statistics for all your variables in a table. Comment on the averages of your variables and anything else you think is interesting or important. Be careful in properly describing the averages of your binary variables. 
5. **Relationship between the Dependent and Independent Variable**: Present a graph showing the relationship between your dependent and primary independent variable. You should present a scatter plot if both of your variables are continuous. If any of the two variables is binary, use a bar plot. Properly label the axes. Summarize what you learn. Verify your observations from the plot by finding and reporting the correlation between your dependent variable and primary independent variable.
6. **Exploring Other Variables**: Present the correlation between all your variables in one or more tables. Discuss any notable patterns that emerge. Given the correlations you find, do you think not accounting for your control variables while studying the relationship between your dependent and primary independent variable might bias your results? If yes, what would be the direction of this bias?

## Submission Checklist

**What needs to be submitted?**

- Filled cover sheet followed by a 2–4-page essay in PDF format that outlines the analysis you performed and summarizes your results. You should include all tables and figures in the body of your essay. (All tables and figures should have a name and number. Also, the write-up should be in essay format, with no bullet points.)
- Your R code that reproduces the analysis you performed.
- The dataset used in the analysis if you made significant changes to the data or are using an external dataset (in excel, csv, or rdata format).

*Submissions need to be made on Canvas.* 

**How to insert tables and figures in your write-up?**

You should prepare your submission in Microsoft Word. You need to manually export all your tables and figures from R. For tables, you can copy from the output and format them as a table in Word (use a fixed-width font like Courier New). You need to export the figures from R and insert them in word. Finally, save your word document as a PDF once you are done. 


## Rubric

```{python}
#| echo: false

import pandas as pd
from IPython.display import display, HTML
from RowSpan import row_span

# Define custom class for table
custom_css = """
<style>
@import url(https://fonts.googleapis.com/css?family=Lato:400,700&display=swap);

.my-table {
    display: block;
    overflow-y: auto;
    height: 650px; 
    width: 100%;
    border-collapse: collapse;
    border: 1px solid #b7b7b7;
}
table.my-table, table.my-table th, table.my-table td {
    font-family: Lato;
}

.my-table td {
    border: 1px solid #b7b7b7; 
    padding: 8px; 
    text-align: left; 
}

.my-table th {
    border: 1px solid #b7b7b7; 
    padding: 8px; 
    text-align: center; 
}

.my-table thead th {
    border: 1px solid #b7b7b7; 
    position: sticky;
    top: 0;
    background-color: #ddd; 
    z-index: 2;
}

# Columns
.my-table td:nth-child(1), .my-table th:nth-child(1) { width: 10%; } 
.my-table td:nth-child(2), .my-table th:nth-child(1) { width: 25%; } 
.my-table td:nth-child(3), .my-table th:nth-child(1) { width: 20%; } 
.my-table td:nth-child(4), .my-table th:nth-child(1) { width: 18%; } 
.my-table td:nth-child(5), .my-table th:nth-child(1) { width: 18%; } 

</style>
"""
# Load and save rubric as html
df = pd.read_excel('submission1-rubric.xlsx', dtype=str)
html_table = df.to_html(escape=False, index=False, na_rep='', classes='my-table')
full_html = custom_css + html_table
with open('submission1-rubric.html', 'w', encoding='utf-8') as f:
    f.write(full_html)

```

<iframe src="submission1-rubric.html" width="100%" height= "650px" scrolling=no></iframe>
