---
title: "Research Project: Interim Submission I"
---

## Introduction

This submission marks the beginning of your research project and is worth 5% of your total grade. As part of this submission, you will identify your research question, the data you will use, and the variables you will analyze. You will also provide a brief justification for why your questions is interesting and important.

Before proceeding, you must review the [Research Project Overview](research-project.qmd) page for detailed guidance on selecting your research question and data. Here is a brief summary of the key criteria to consider:

- Choose a question that is "causal" in nature. In particular, your question should examine the effect of one variable (**the primary independent variable**) on another (**the dependent variable**).
- In addition to your primary independent and dependent variables, you should identify **at least two control variables**. See the [section on variables](research-project.qmd#variables) on the [overview](research-project.qmd) page for more details. 
- Use a dataset that includes **at least 100 observations** and all the variables you need for your analysis.

## Submission Checklist

For the submission, you need to fill and submit the [Template for Submission 1](submission1-template.docx) in PDF format. Here is an [example](submission1-example.pdf) to get you started. You must also upload your data in CSV or excel format if you are using an external dataset. 

**What needs to be submitted?**

- Filled Template for Submission 1 in PDF format
- The dataset in CSV or excel format if using an external dataset.

*Submissions need to be made on Canvas. Any member of the group can submit on your group's behalf.*

<!-- ## Rubric
<iframe src="submission1-rubric.html" width="100%" height= "650px" scrolling=no></iframe> -->
